# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-16 23:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_auto_20180816_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Pedido'),
        ),
    ]
