# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-17 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0072_auto_20180816_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('valor', models.CharField(blank=True, default='0.00', max_length=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Debito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('valor', models.CharField(blank=True, default='0.00', max_length=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('CREDITO', 'CREDITO'), ('DEBITO', 'DEBITO')], max_length=50)),
                ('valor', models.CharField(blank=True, default='0.00', max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Operacao',
                'verbose_name_plural': 'Operacoes',
            },
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='creditos',
            field=models.CharField(blank=True, default='0.00', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='operacao',
            name='favorecido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Estabelecimento'),
        ),
        migrations.AddField(
            model_name='debito',
            name='estabelecimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Estabelecimento'),
        ),
        migrations.AddField(
            model_name='credito',
            name='estabelecimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Estabelecimento'),
        ),
    ]
